version: 0.1

# Default environment (Staging)
default:
  deploy:
    parameters:
      capabilities:
        - "CAPABILITY_IAM"
        - "CAPABILITY_AUTO_EXPAND"
        - "CAPABILITY_NAMED_IAM"
      confirm_changeset: false
      stack_name: "chow-tap-staging"
      region: "us-east-1"
      resolve_s3: true
      s3_prefix: "chow-tap-staging"
      parameter_overrides: >
        Stage=staging
        PoolId=us-east-1_4jPibnfi1
        ClientId=5q0la736qnon8t8jitr9noibfe
        ClientSecret=u3t2r1d70sthsos920nok173uf4dvnf6nnqfjjii9pje71j7dfb

# Production environment
prod:
  deploy:
    parameters:
      capabilities:
        - "CAPABILITY_IAM"
        - "CAPABILITY_AUTO_EXPAND"
        - "CAPABILITY_NAMED_IAM"
      confirm_changeset: false
      stack_name: "chow-tap-prod"
      region: "us-east-1"
      resolve_s3: true
      s3_prefix: "chow-tap-prod"
      parameter_overrides: >
        Stage=prod
        PoolId=us-east-1_4jPibnfi1
        ClientId=5q0la736qnon8t8jitr9noibfe
        ClientSecret=u3t2r1d70sthsos920nok173uf4dvnf6nnqfjjii9pje71j7dfb