version: 0.1

# Default environment (Staging)
default:
  deploy:
    parameters:
      capabilities:
        - "CAPABILITY_IAM"
        - "CAPABILITY_AUTO_EXPAND"
        - "CAPABILITY_NAMED_IAM"
      confirm_changeset: false
      stack_name: "chow-tap-staging"
      region: "us-east-1"
      resolve_s3: true
      s3_prefix: "chow-tap-staging"
      parameter_overrides: >
        Stage=staging
        PoolId={{resolve:ssm:/chow-tap/prod/POOL_ID:1}}
        ClientId={{resolve:ssm:/chow-tap/prod/CLIENT_ID:1}}
        ClientSecret={{resolve:ssm:/chow-tap/prod/CLIENT_SECRET:1}}

# Production environment
prod:
  deploy:
    parameters:
      capabilities:
        - "CAPABILITY_IAM"
        - "CAPABILITY_AUTO_EXPAND"
        - "CAPABILITY_NAMED_IAM"
      confirm_changeset: false
      stack_name: "chow-tap-prod"
      region: "us-east-1"
      resolve_s3: true
      s3_prefix: "chow-tap-prod"
      parameter_overrides: >
        Stage=prod
        PoolId={{resolve:ssm:/chow-tap/prod/POOL_ID:1}}
        ClientId={{resolve:ssm:/chow-tap/prod/CLIENT_ID:1}}
        ClientSecret={{resolve:ssm:/chow-tap/prod/CLIENT_SECRET:1}}