version: 0.1

# Default environment (Staging)
default:
  deploy:
    parameters:
      capabilities:
        - "CAPABILITY_IAM"
        - "CAPABILITY_AUTO_EXPAND"
        - "CAPABILITY_NAMED_IAM"
      confirm_changeset: false
      stack_name: "chow-tap-staging"
      region: "us-east-1"
      resolve_s3: true
      s3_prefix: "chow-tap-staging"
      parameter_overrides: >
        Stage=staging
        UserPoolId=us-east-1_N69lOUMSh
        AppClientId=18et6apv77lom9ka7ugthcpndq

# Production environment
prod:
  deploy:
    parameters:
      capabilities:
        - "CAPABILITY_IAM"
        - "CAPABILITY_AUTO_EXPAND"
        - "CAPABILITY_NAMED_IAM"
      confirm_changeset: false
      stack_name: "chow-tap-prod"
      region: "us-east-1"
      resolve_s3: true
      s3_prefix: "chow-tap-prod"
      parameter_overrides: >
        Stage=prod
        UserPoolId=us-east-1_N69lOUMSh
        AppClientId=18et6apv77lom9ka7ugthcpndq